#ifndef _FUNCTION_CODES_H_
#define _FUNCTION_CODES_H_

#define SERVER_REQUEST_MESSAGESERVER_ID  10000
#define SERVER_SEND_MESSAGESERVER_ID     10001
#define SERVER_USER_LOGIN              10002
#define USER_LOGIN_SUCCESS             10003
#define USER_LOGIN_FAIL                10004
#define SERVER_USER_LOGOUT             10005
#define SERVER_CLIENT_FORCE_CLOSE      10006
#define SERVER_FORWARD_MESSAGE_STATE  7000
#define SERVER_FORWARD_MESSAGE_CLIENT 8000
#define SERVER_FORWARD_MESSAGE_DB     9000
#define SERVER_FORWARD_MESSAGE_AISERV 9900

#define USER_AGENT_EVENT_UPDATE_SEND_TO_ALL        9999
//Game/chat function codes 
#define PLAYER_REQUEST_LOGON       11000

#define EVENT_SPECFIC_MESSAGE_LOW  15000
#define EVENT_SPECFIC_MESSAGE_HIGH 25000

#define EVENT_START                15001
#define EVENT_END                  15002
#define EVENT_TRANSACTION          15003
#define EVENT_USER_CREATE_ORDER    15004
#define EVENT_USER_CANCEL_ORDER    15005
#define EVENT_USER_MODIFY_ORDER    15006
#define EVENT_PLAYER_JOINS_GROUP   15007
#define EVENT_PLAYER_LEAVES_GROUP  15008
#define EVENT_PLAYER_JOINS_EVENT   15009
#define EVENT_PLAYER_QUITS_EVENT   15010

#define EVENT_EVENT_CREATES_GROUP  15011
#define EVENT_EVENT_REMOVES_GROUP  15012
#define EVENT_EVENT_UPDATES_MARKET 15013

#define EVENT_NEW_PLAYER           15014
#define EVENT_PLAYER_LOGIN         15015
#define EVENT_CREATED_BY_ADMIN     15016
#define EVENT_REMOVE_EVENT         15017
#define EVENT_UPDATE_ORDER_STATUS  15018

#define EVENT_PLAYER_LOADED_APP    15500
#define SERVER_UPDATE_ORDER_QTY    15501
#define SERVER_UPDATE_ORDER_PRICE  15502
#define UPDATE_CLIENT_INFO         15503



//ADMIN FUNCTIONS TO BE USED BY TEAM TO MANAGE EVENTS/GROUPS/PLAYERS

#define ADMIN_CREATE_EVENT         20001
#define ADMIN_REMOVE_EVENT         21000
#define ADMIN_START_EVENT          22000
#define ADMIN_STOP_EVENT           23000

#define ADMIN_ADD_COMPETITOR       24000
#define ADMIN_REMOVE_COMPETITOR    24100
#define PING_USER_STILL_CONNECTED  25000
#define PING_USER_CHALLENGE_RESP   25001

/* 
 MESSAGE FORMAT
 
 FUNCTION_CODE
 AgentID - can be 0 if logging in
 EventID - can be 0 if no events have been joined
 GroupID - can be 0 if no event have been joined.
 PlayerID -- Used for identification and ability to return message
 
 DATA RELATED TO FUNCTION_CODE
 */
#endif

